### ISSUE TITLE
少了个kube-state-metrics

### ISSUE THREAD

**Issue by X-Mars** [honest1y/k8s-prom#1]
大佬，我已经跑起来了，可惜少一个kube-state-metrics啊。

**Comment by honest1y** [comment]
> 大佬，我已经跑起来了，可惜少一个kube-state-metrics啊。

KSM可以用官方仓库的yaml直接部署
https://github.com/kubernetes/kube-state-metrics/tree/master/examples/standard

**Comment by X-Mars** [comment]
这个我已经安装了，可能我太菜，安装后targets 看不到

**Comment by X-Mars** [comment]
可以关闭了  我慢慢研究吧   谢谢大佬
